name: accounting_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.10
  googleapis: ^13.1.0
  
  # دعم اللغة العربية والترجمة
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # أيقونات وأساسيات
  cupertino_icons: ^1.0.8

  # قاعدة البيانات (SQLite) مع دعم الويب وسطح المكتب
  sqflite: ^2.4.3
  sqflite_common_ffi: ^2.3.4
  sqflite_common_ffi_web: ^0.4.5
  path_provider: ^2.1.6
  path: ^1.9.0

  # طباعة وتصدير PDF
  pdf: ^3.13.0
  printing: ^5.15.0
  
<<<<<<< HEAD
  # اختيار الملفات والمشاركة (بمسافات صحيحة)
=======
  # اختيار الملفات والمشاركة - compatible versions
>>>>>>> 05175bb157154d7d4348a5642bc8c9b8f4587049
  file_picker: ^11.0.2
  share_plus: ^10.1.4
  # خطوط جميلة
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
