name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.0' # 🚀 تم فك الأسر والترقية للنسخة الحديثة (تضم Dart 3.8)

      - name: Clean and Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Bulletproof compileSdk patch
        run: |
          # إضافة (|| true) تمنع لينكس من إيقاف البناء في حال كان امتداد الملف غير موجود
          sed -i 's/compileSdk = 34/compileSdk = 36/g' android/app/build.gradle.kts || true
          sed -i 's/targetSdk = 34/targetSdk = 36/g' android/app/build.gradle.kts || true
          sed -i 's/compileSdk 34/compileSdk 36/g' android/app/build.gradle || true
          sed -i 's/targetSdk 34/targetSdk 36/g' android/app/build.gradle || true

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk